[build]
command = "npm install"

[deploy]
startCommand = "node bot-debug.js"

[env]
NODE_ENV = "production"
DATABASE_URL = "postgresql://postgres:isRxzsszifQZEcxCgiBwJtVBEpgIaIbZ@postgres.railway.internal:5432/railway"